         "EOF expected",
         "ident expected",
         "number expected",
         "nl expected",
         "\"#!\" expected",
         "\".,\" expected",
         "\".sh\" expected",
         "not expected",
         "unexpected symbol in dotkoma",
